FROM python:3.8-slim as builder

ARG DEBIAN_FRONTEND=noninteractive

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Upgrade pip first dependencies
RUN pip install --upgrade pip

COPY . /app

RUN pip wheel --no-cache-dir --no-deps --wheel-dir /app/wheels -r ./app/requirements.txt

# pull official base image
FROM python:3.8-slim

# create the appropriate directories
ENV HOME=/home/app
ENV APP_HOME=/home/app/app

# Place webapp files here and use a non-root user
RUN useradd --create-home app

# Set working dir to the new home
WORKDIR $HOME

# install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends netcat
COPY --from=builder /app/wheels /wheels
COPY --from=builder /app/requirements.txt .
RUN pip install --upgrade pip
RUN pip install --no-cache /wheels/*

RUN mkdir -p $APP_HOME
#COPY ./entrypoint.prod.sh $APP_HOME
COPY ./app $APP_HOME

# chown all the files to the app user
RUN chown -R app:app $APP_HOME

USER app

EXPOSE 5000

ENV FLASK_APP=app

ENTRYPOINT ["sh", "-c", "$APP_HOME/entrypoint.prod.sh"]

# ENTRYPOINT ["flask", "run", "--host=0.0.0.0"]
