version: "3.7"

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: flask run --host=0.0.0.0
    ports:
      - 5000:5000
    env_file: .env
    volumes:
      - ./app:/home/webapp/app
